### PR TITLE
Testing out Provider functions instead of Services

### PR DESCRIPTION
**Pull request by evandam**
Hi Tealium Team!

I am new to Tealium and looking into using it with a new AngularJS application at work. This pull request revolves around using the Provider recipe of Angular instead of the Service or Factory.

Providers can be injected into an app's config block that runs during bootstrap, and can then be specific to the application. The main benefit I see here is that tealium.js and tealium-data.js does not need to be modified. Then, multiple projects may reference these same files but configure them to their own needs.

My changes are not complete or tested, but I wanted to propose the idea - this is my first pull request!

Thank you!

### CODE REVIEW

**Comment by tygavin** [comment]
Thanks Evan.  The Provider recipe seems like a good way to go.

Quick question for you.. Can you provide a few details on what is "not complete or tested"?

**Comment by tygavin** [comment]
@evandam Thanks again for your contributions.  Just want to check to understand what you mean by "changes are not complete."

**Comment by evandam** [comment]
Hi,

Thanks for the response! I saw there's some test/sample files in there, but I have not run them. I'm planning on testing and tweaking the changes over the next day or two, though. What I sent earlier was really just to demonstrate how the provider could look.

**Comment by evandam** [comment]
Hi Ty,

I was able to clean up my code a bit and the test page looks to be functional. I also added a directive that binds that element's click event to call the link function. Since none of these files would need to be changed, this can all also be merged into a single file that would be easier to include on a page.

**Comment by tygavin** [comment]
@evandam This looks great.  I'd like to just go ahead and merge, but there are a few items (specifically package.json and .gitignore) that may not make sense in this repo.  Are you able to remove these from the pull request?  I'm happy to update the Readme to link to your repo and give you a shout out there for the recent updates and list you as a contributor.

**Comment by evandam** [comment]
@tygavin Those files were just for running a small local server to test and they've been removed. 

Thanks!

**Pull request merged**
